spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root  
    password: root
  session:
    store-type: none
security:
  basic:
    enabled: false
    